const data = [
  {
    id: 1,
    name: "Raptor",
    price: 500,
    img_src: "./assets/ustnik.jpg",
    available: true,
    instr_type: "Alto",
    style: "JAZZ",
    tip_open: 1.6,
    productPage: "",
    description: "",
  },
  {
    id: 2,
    name: "Diango",
    price: 1500,
    img_src: "./assets/ustnik.jpg",
    available: false,
    instr_type: "Tenor",
    style: "JAZZ",
    tip_open: 2.0,
    productPage: "",
    description: "",
  },
  {
    id: 3,
    name: "XYZ",
    price: 750,
    img_src: "./assets/ustnik.jpg",
    available: true,
    instr_type: "Alto",
    style: "JAZZ",
    tip_open: 1.4,
    productPage: "",
    description: "",
  },
  {
    id: 4,
    name: "ABC",
    price: 450,
    img_src: "./assets/ustnik.jpg",
    available: true,
    instr_type: "Alto",
    style: "POP",
    tip_open: 1.6,
    productPage: "",
    description: "",
  },
  {
    id: 5,
    name: "SHJK",
    price: 450,
    img_src: "./assets/ustnik.jpg",
    available: true,
    instr_type: "Alto",
    style: "POP",
    tip_open: 1.6,
    productPage: "",
    description: "",
  },
  {
    id: 6,
    name: "FSD",
    price: 550,
    img_src: "./assets/ustnik.jpg",
    available: true,
    instr_type: "Soprano",
    style: "JAZZ",
    tip_open: 1.6,
    productPage: "",
    description: "",
  },
  {
    id: 7,
    name: "LKHJGF",
    price: 750,
    img_src: "./assets/ustnik.jpg",
    available: true,
    instr_type: "Baritone",
    style: "JAZZ",
    tip_open: 2.0,
    productPage: "",
    description: "",
  },
];

export default data;
