const data = [
    {
        id: 1,
        name: "Raptor",
        price: 500,
        img_src: "./assets/ustnik.jpg",
        available: true,
        instr_type: "ALT",
        style: "JAZZ",
        tip_open: 1.6,
    },
    {
        id: 2,
        name: "Diango",
        price: 1500,
        img_src: "",
        available: false,
        instr_type: "TENOR",
        style: "JAZZ",
        tip_open: 2.0,
    },
    {
        id: 3,
        name: "XYZ",
        price: 750,
        img_src: "",
        available: true,
        instr_type: "ALT",
        style: "JAZZ",
        tip_open: 1.4,
    },
    {
        id: 4,
        name: "ABC",
        price: 450,
        img_src: "",
        available: true,
        instr_type: "ALT",
        style: "POP",
        tip_open: 1.6,
    },
    {
        id: 5,
        name: "SHJK",
        price: 450,
        img_src: "",
        available: true,
        instr_type: "ALT",
        style: "POP",
        tip_open: 1.6,
    },
    {
        id: 6,
        name: "FSD",
        price: 550,
        img_src: "",
        available: true,
        instr_type: "SOPR",
        style: "JAZZ",
        tip_open: 1.6,
    }
];

export default data;